### ISSUE TITLE
定时任务 DefaultPriorityQueue.remove 指针异常

### ISSUE THREAD

**Issue by Sunnus3** [Sunnus3/gecco-schedule#1]
情况:
 线程数量: 1 (4个线程是无此现象)
 任务数量 : 21
 任务提交方式: scheduleAtFixedRate
 异常信息: 
java.lang.NullPointerException: null
	at com.geccocrawler.gecco.spider.ScheduleSpiderExecutor$1.compare(ScheduleSpiderExecutor.java:23) ~[gecco-core-1.3.1.jar:1.3.1]
	at com.geccocrawler.gecco.spider.ScheduleSpiderExecutor$1.compare(ScheduleSpiderExecutor.java:20) ~[gecco-core-1.3.1.jar:1.3.1]
	at com.geccocrawler.gecco.spider.internal.DefaultPriorityQueue.bubbleDown(DefaultPriorityQueue.java:238) ~[gecco-core-1.3.1.jar:1.3.1]
	at com.geccocrawler.gecco.spider.internal.DefaultPriorityQueue.poll(DefaultPriorityQueue.java:96) ~[gecco-core-1.3.1.jar:1.3.1]
	at com.geccocrawler.gecco.spider.internal.DefaultPriorityQueue.poll(DefaultPriorityQueue.java:11) ~[gecco-core-1.3.1.jar:1.3.1]
	at java.util.AbstractQueue.remove(AbstractQueue.java:113) ~[na:1.8.0_161]
	at com.geccocrawler.gecco.spider.ScheduleSpiderExecutor.pollScheduledTask(ScheduleSpiderExecutor.java:63) ~[gecco-core-1.3.1.jar:1.3.1]
	at com.geccocrawler.gecco.spider.SingleSpiderExecutor.fetchFormScheduledTaskQueue(SingleSpiderExecutor.java:286) ~[gecco-core-1.3.1.jar:1.3.1]
	at com.geccocrawler.gecco.spider.SingleSpiderExecutor.runAllTasks(SingleSpiderExecutor.java:247) ~[gecco-core-1.3.1.jar:1.3.1]
	at com.geccocrawler.gecco.spider.SpiderLoop.run(SpiderLoop.java:43) ~[gecco-core-1.3.1.jar:1.3.1]
	at com.geccocrawler.gecco.spider.SingleSpiderExecutor$1.run(SingleSpiderExecutor.java:125) [gecco-core-1.3.1.jar:1.3.1]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]

**Comment by Sunnus3** [comment]
重现是没有出现,先解决 #2
